config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:new, :create, :edit, :update, :destroy, :show, :search]
  get "books/search" => "books#search",  as: :search_book
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  mount_uploader :image, ImageUploader

  validates :name, uniqueness: { scope: [:author, :publisher] }
  validates :name, :author, :publisher, presence: true
  validates :stars, numericality: { less_than: 6 }

  validates_processing_of :image
  validate :image_size_validation

  private

  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    http_basic_authenticate_with name: "42", password: "42", only: :destroy
    before_action :set_book, only: [:edit, :update, :destroy, :show]

    def index
      @lastest_add_books = Book.all.order(created_at: :desc )
    end

    def search
      search_name = "%#{params[:name]}%"
      @books = Book.where "name like ?", search_name
    end

    def show
      renderiza :show
    end

    def new
      @book = Book.new
      renderiza :new
    end

    def create
      @book = Book.new book_params
      if @book.save
        flash[:notice] = "Livro \"#{@book.name}\" salvo com sucesso!"
        redirect_to root_url
      else
        renderiza :new
      end
    end

    def edit
      renderiza :edit
    end

    def update
      if @book.update book_params
        flash[:notice] = "Livro \"#{@book.name}\" atualizado com sucesso!"
        redirect_to root_url
      else
        renderiza :new
      end
    end

    def destroy
      if @book.destroy
        flash[:notice] = "Livro \"#{@book.name}\" deletado!"
        redirect_to root_url
      end
    end

    private

    def book_params
      params.require(:book).permit(:name, :author, :publisher, :stars, :about, :image)
    end

    def renderiza(view)
      render view
    end

    def set_book
      id = params[:id]
      @book = Book.find(id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.slim
.col
  = image_tag book.image.thumb, class: "float-left"
  h4
    = link_to book.name, book
  h6
    = book.author
  small
    | Nota: 
    = book.stars

app/views/books/_form.html.slim
- @book.errors.full_messages.each do |messages|
  .alert.alert-danger
    = messages
= form_for @book do |b|
  .form-group
    = b.label :name
    = b.text_field :name, class: "form-control"
  .form-group
    = b.label :author
    = b.text_field :author, class: "form-control"
  .form-group
    = b.label :publisher
    = b.text_field :publisher, class: "form-control"
  .form-group
    = b.label :stars
    = b.number_field :stars, step: 1, class: "form-control"
  .form-group
    = b.label :about
    = b.text_area :about, rows: 4, class: "form-control"
  .form-group
    = b.label :image
    = b.file_field :image, class: "form-control"
  div[style="margin-top: 0.2cm;"]
    = b.submit action_text, class: "btn btn-primary form-control"

app/views/books/busca.html.slim
.form-group
  .row
    = render @books

app/views/books/edit.html.slim
= render partial: "form", locals: { action_text: "Editar Livro" }

app/views/books/index.html.slim
- if  flash[:notice]
  .alert.alert-success
    = flash[:notice]
.form-group
  h5
    | Últimos livros adicionados
  .row
    = render @lastest_add_books
= link_to "+ Adicionar Livro", new_book_path

app/views/books/new.html.slim
= render partial: "form", locals: { action_text: "Adicionar Livro" }

app/views/books/search.html.erb
<div class="form-group">
  <div class="row">
    <%= render @books %>
  </div>
</div>

app/views/books/search.html.slim
.form-group
  .row
    = render @books

app/views/books/show.html.slim
= image_tag @book.image.thumb
h2
  = @book.name
h6
  |  by
  = @book.author
  |  (
  = @book.publisher
  | )
small
  = @book.stars
p
  | "
  = @book.about
  | "
.btn-group
  = link_to "Editar Livro >", edit_book_path
  = button_to "Excluir Livro", @book,
                                 method: :delete,
                                 class: "btn btn-danger btn-sm btn-group btn-right",
                                 data: { confirm: "Quer realmente apagar o livro \"#{@book.name}\" ?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guia42</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= nav_bar brand: "Guia 42", brand_link: root_url do %>
      <%= form_tag search_book_path,
                    method: :get,
                    class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :name, @search_name, class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn btn-primary"%>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>